"""fix presentation relationship

Revision ID: 1fb6c07450f5
Revises: 567a823467d9
Create Date: 2016-03-25 10:39:50.819272

"""

# revision identifiers, used by Alembic.
revision = '1fb6c07450f5'
down_revision = '567a823467d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'presentation_ibfk_1', 'presentation', type_='foreignkey')
    op.create_foreign_key(None, 'presentation', 'slideshow', ['slideshow_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presentation', type_='foreignkey')
    op.create_foreign_key(u'presentation_ibfk_1', 'presentation', 'user', ['slideshow_id'], ['id'])
    ### end Alembic commands ###
