"""Add timestamps to slideshows

Revision ID: 23b31b63e72a
Revises: eeb0be29a3eb
Create Date: 2016-03-22 12:15:33.524259

"""

# revision identifiers, used by Alembic.
revision = '23b31b63e72a'
down_revision = 'eeb0be29a3eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slideshow', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('slideshow', sa.Column('last_presented', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slideshow', 'last_presented')
    op.drop_column('slideshow', 'created')
    ### end Alembic commands ###
