"""index presentations by hash

Revision ID: 32ec678df238
Revises: 89eae1efab85
Create Date: 2016-03-27 15:29:27.749434

"""

# revision identifiers, used by Alembic.
revision = '32ec678df238'
down_revision = '89eae1efab85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_presentation_slideshow_hash'), 'presentation', ['slideshow_hash'], unique=True)
    op.drop_index('slideshow_hash', table_name='presentation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('slideshow_hash', 'presentation', ['slideshow_hash'], unique=True)
    op.drop_index(op.f('ix_presentation_slideshow_hash'), table_name='presentation')
    ### end Alembic commands ###
