"""add full name to user

Revision ID: 4b54d3611475
Revises: 23b31b63e72a
Create Date: 2016-03-25 09:53:42.285706

"""

# revision identifiers, used by Alembic.
revision = '4b54d3611475'
down_revision = '23b31b63e72a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
