"""store presentation state

Revision ID: a9fef51e3fb3
Revises: bfd7c9bd3765
Create Date: 2016-03-27 16:34:28.854166

"""

# revision identifiers, used by Alembic.
revision = 'a9fef51e3fb3'
down_revision = 'bfd7c9bd3765'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation', sa.Column('state', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation', 'state')
    ### end Alembic commands ###
