"""add client count to presentation

Revision ID: bfd7c9bd3765
Revises: 32ec678df238
Create Date: 2016-03-27 15:31:30.761307

"""

# revision identifiers, used by Alembic.
revision = 'bfd7c9bd3765'
down_revision = '32ec678df238'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation', sa.Column('clients', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation', 'clients')
    ### end Alembic commands ###
