"""Add description to slideshow

Revision ID: eeb0be29a3eb
Revises: edf5df9967b6
Create Date: 2016-03-19 19:23:49.759383

"""

# revision identifiers, used by Alembic.
revision = 'eeb0be29a3eb'
down_revision = 'edf5df9967b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slideshow', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slideshow', 'description')
    ### end Alembic commands ###
