"""add creation date to presentations

Revision ID: f4fd1689bf7d
Revises: a9fef51e3fb3
Create Date: 2016-03-27 19:20:36.410285

"""

# revision identifiers, used by Alembic.
revision = 'f4fd1689bf7d'
down_revision = 'a9fef51e3fb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation', sa.Column('created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_presentation_created'), 'presentation', ['created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presentation_created'), table_name='presentation')
    op.drop_column('presentation', 'created')
    ### end Alembic commands ###
